/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type SubStepType = 'horizon' | 'api' | 'phone' | 'tool' | 'sms' | 'outcome' | 'custom';

export interface ChatMessage {
  sender: 'agent' | 'recipient';
  name: string;
  text: string;
}

// Where a sub-step sits in the long-horizon contact loop. Internal sub-steps
// (horizon/api/tool) go straight from pending to done; outbound contact
// sub-steps (phone/sms/email) sit in awaiting_reply until a webhook resolves them.
export type ContactStatus = 'pending' | 'awaiting_reply' | 'done';

/**
 * Where a sub-step's `chatLog` actually came from. The timeline is meant to be a record of
 * what the agent really did, so a conversation that never happened must not render
 * identically to one that did.
 *
 *   'inbound'     a real reply arrived from a provider webhook
 *   'synthesized' generated by the model (or a canned fallback) via force-advance
 *   'fixture'     shipped with the claim template; nobody was ever contacted
 *
 * Treat an ABSENT value on a sub-step that already has a `chatLog` as untrusted
 * provenance -- i.e. show it as not-real rather than assuming it was inbound.
 */
export type ReplySource = 'inbound' | 'synthesized' | 'fixture';

export interface SubStep {
  id: string;
  type: SubStepType;
  systemName: string; // e.g. "Horizon", "Payer portal", "EHR", "Payer", "Provider", "Scheduling", "Patient", "Outcome"
  techType?: string; // e.g. "API", "Phone", "SMS", "Tool", "Workflow", "Calendar"
  description: string;
  chatLog?: ChatMessage[];
  outcomeLabel?: string;
  contactStatus?: ContactStatus;
  replySource?: ReplySource;
}

export interface TimelineStep {
  id: string;
  timeLabel: string; // e.g. "Day 1", "+5 minutes", "Day 2", "+45 minutes"
  signal: string;
  agentMemory: string;
  subSteps: SubStep[];
  status: 'completed' | 'active' | 'pending';
}

export interface ClaimResolutionCheck {
  checkNumber: string;
  date: string;
  amount: number;
  payTo: string;
  memo: string;
  signature: string;
  resolutionText: string;
}

export interface ClaimTemplateInfo {
  key: string;
  id: string;
  claimantName: string;
  claimType: string;
  claimAmount: number;
  status: string;
}

// What the agent is currently waiting on. Mirrors the `claims:awaiting` document
// so the UI can show "waiting for reply" state and elapsed time.
export interface AwaitingContact {
  claimId: string;
  stepIndex: number;
  subStepId: string;
  channel: 'sms' | 'call' | 'email';
  lookupKey: string;
  sentAt: string; // ISO timestamp
  attempt: number;
}

export interface Claim {
  id: string;
  claimantName: string;
  claimType: string;
  claimAmount: number;
  status: 'INTAKE' | 'PROCESSING' | 'EVIDENCE_REQUEST' | 'PAYER_VERIFICATION' | 'AWAITING_APPROVAL' | 'RESOLVED' | 'CLOSED';
  timeline: TimelineStep[];
  currentStepIndex: number;
  description: string;
  policyNumber: string;
  resolutionCheck?: ClaimResolutionCheck;
  // Monotonic write counter. NOT a concurrency guard -- nothing compares it, so it does
  // not prevent a clobber. The MongoDB mutex (`withClaimLock`) is what actually serializes
  // mutations. Used as an entropy component for force-advance event ids, and as a cheap
  // "did this change?" signal. Do not skip the lock on the strength of this field.
  version: number;
  claimantPhone?: string;
  claimantEmail?: string;

  /**
   * Cumulative facts learned across contacts (persisted on `claims:active`).
   * Seeded from the active step's template memory and appended after each reply so
   * the next call/SMS sees prior context, not only that step's static string.
   */
  workingMemory?: string;

  /** Shop estimate before negotiation (set when a live concession updates claimAmount). */
  initialShopQuote?: number;
  /** Dollars the shop conceded in negotiation (from the real call / force-advance reply). */
  shopConcession?: number;

  // Drafted when the claim enters AWAITING_APPROVAL, BEFORE any money moves, so the
  // adjuster can see exactly what they are signing off on. The authoritative figures
  // still land in `resolutionCheck` once approval actually releases the settlement.
  proposedDeductible?: number;
  proposedPayout?: number;

  /** Stable id for this interaction run — survives refresh; archived under claims:session:* */
  sessionId?: string;
  /** ISO timestamp when this interaction session started (claim load). */
  sessionStartedAt?: string;
}

/** End-of-run (or live snapshot) of a full claim interaction, stored in MongoDB. */
export type ClaimSessionEndReason = 'active' | 'stopped' | 'resolved' | 'replaced';

export interface ClaimSessionRecord {
  sessionId: string;
  claimId: string;
  claimantName: string;
  claimType: string;
  status: string;
  startedAt: string;
  updatedAt: string;
  endedAt?: string;
  endReason: ClaimSessionEndReason;
  claim: Claim;
  awaiting?: AwaitingContact | null;
}

export interface ClaimSessionSummary {
  sessionId: string;
  claimId: string;
  claimantName: string;
  claimType: string;
  status: string;
  startedAt: string;
  updatedAt: string;
  endedAt?: string;
  endReason: ClaimSessionEndReason;
  claimAmount: number;
  currentStepIndex: number;
  stepCount: number;
}

// Live vs mock state per outbound channel, surfaced in the UI so it's obvious
// whether the running app can actually contact anyone.
export interface VendorStatus {
  sms: boolean;
  call: boolean;
  email: boolean;
  /** The language model (OpenAI). Named by role, not vendor, so swapping providers
   *  again does not ripple into the UI. */
  llm: boolean;
}

// --- Agent memory (`agent_memory`) ------------------------------------------
// Long-term memory: what the agent learned on EARLIER claims. Distinct from
// `Claim.workingMemory`, which is scoped to one claim and dies with it.

export type MemoryKind = 'contact_outcome' | 'negotiation' | 'settlement' | 'policy_fact';

/**
 * Which retrieval path actually served a recall. Surfaced rather than hidden: a keyword
 * hit must not be presentable as semantic search.
 */
export type RecallMode = 'vector' | 'keyword';

export interface AgentMemoryStatus {
  /** What the next recall will attempt first. */
  mode: RecallMode;
  /** Atlas Vector Search index believed usable (Atlas + embeddings, not yet demoted). */
  vectorReady: boolean;
  /** Embeddings available at all — false under MOCK_MODE or without an OpenAI key. */
  embeddings: boolean;
  total: number;
}

export interface AgentMemoryEntry {
  id: string;
  kind: MemoryKind;
  text: string;
  counterparty: string;
  claimType: string;
  claimId: string;
  /** The structured outcome behind `text`, e.g. { concession: 450, quoteAfter: 8750 }. */
  facts: Record<string, number | string | boolean | null>;
  createdAt: string;
  score: number;
  mode: RecallMode;
}

// --- Checkpoints (`checkpoints`) --------------------------------------------
// One entry per state transition, in LangGraph's checkpointer shape. The lineage is
// what lets a restart resume mid-claim instead of cold-starting.

export type CheckpointReason =
  | 'claim_loaded'
  | 'advance'
  | 'contact_dispatched'
  | 'reply_resolved'
  | 'awaiting_approval'
  | 'finalized'
  | 'stopped'
  | 'restored';

export interface CheckpointSummary {
  checkpointId: string;
  parentCheckpointId: string | null;
  /** The claim id: one long-horizon claim is one graph thread. */
  threadId: string;
  ts: string;
  reason: CheckpointReason;
  status: string;
  stepIndex: number;
  subStepId: string | null;
  version: number;
  claimantName: string;
  claimAmount: number;
  awaitingChannel: string | null;
}

// One document in the MongoDB `kv` collection, as the dashboard sees it.
export interface DbKeyInfo {
  key: string; // the document's _id
  /** Logical shape of `value` in BSON: a string, an array, a de-duplicated array, or a
   *  nested subdocument. `document` is what a whole `Claim` is stored as. */
  type: 'string' | 'array' | 'set' | 'document';
  value: string; // JSON formatted or raw string
  ttl: number | null; // seconds until `expiresAt`, null if the document never expires
  size: number; // real BSON size of the document in bytes
  locked: boolean;
}

export interface DbLog {
  timestamp: string;
  level: 'INFO' | 'COMMAND' | 'ERROR' | 'PUB_SUB';
  msg: string;
}

export interface DbPubSubMsg {
  timestamp: string;
  channel: string;
  message: string;
}

export interface DbStats {
  usedMemory: number; // dbStats.dataSize
  totalKeys: number;
  uptimeSeconds: number;
  operationsProcessed: number;
  connectedClients: number;
}
